package nl

const (
	GTP5G_ROLE_UPF = iota
	GTP5G_ROLE_RAN
)

const (
	IFLA_GTP5G_UNSPEC = iota

	IFLA_GTP5G_FD1
	IFLA_GTP5G_PDR_HASHSIZE
	IFLA_GTP5G_ROLE

	__IFLA_GTP5G_MAX
	IFLA_GTP5G_MAX = __IFLA_GTP5G_MAX - 1
)

const (
	GTP5G_CMD_UNSPEC = iota

	GTP5G_CMD_ADD_PDR
	GTP5G_CMD_ADD_FAR
	GTP5G_CMD_ADD_QER

	GTP5G_CMD_DEL_PDR
	GTP5G_CMD_DEL_FAR
	GTP5G_CMD_DEL_QER

	GTP5G_CMD_GET_PDR
	GTP5G_CMD_GET_FAR
	GTP5G_CMD_GET_QER

	__GTP5G_CMD_MAX
	GTP5G_CMD_MAX = __GTP5G_CMD_MAX - 1
)

const (
	GTP5G_ATTR_MAX = 0x10
)

const (
	GTP5G_LINK = iota + 1
	GTP5G_NET_NS_FD
)

const (
	GTP5G_PDR_ID = iota + 3
	GTP5G_PDR_PRECEDENCE
	GTP5G_PDR_PDI
	GTP5G_OUTER_HEADER_REMOVAL
	GTP5G_PDR_FAR_ID

	GTP5G_PDR_ROLE_ADDR_IPV4

	GTP5G_PDR_UNIX_SOCKET_PATH

	GTP5G_PDR_QER_ID

	__GTP5G_PDR_ATTR_MAX
	GTP5G_PDR_ATTR_MAX = __GTP5G_PDR_ATTR_MAX - 1
)

const (
	GTP5G_PDI_UE_ADDR_IPV4 = iota + 1
	GTP5G_PDI_F_TEID
	GTP5G_PDI_SDF_FILTER

	__GTP5G_PDI_ATTR_MAX
	GTP5G_PDI_ATTR_MAX = __GTP5G_PDI_ATTR_MAX - 1
)

const (
	GTP5G_F_TEID_I_TEID = iota + 1
	GTP5G_F_TEID_GTPU_ADDR_IPV4

	__GTP5G_F_TEID_ATTR_MAX
	GTP5G_F_TEID_ATTR_MAX = __GTP5G_F_TEID_ATTR_MAX - 1
)

const (
	GTP5G_SDF_FILTER_FLOW_DESCRIPTION = iota + 1
	GTP5G_SDF_FILTER_TOS_TRAFFIC_CLASS
	GTP5G_SDF_FILTER_SECURITY_PARAMETER_INDEX
	GTP5G_SDF_FILTER_FLOW_LABEL
	GTP5G_SDF_FILTER_SDF_FILTER_ID

	__GTP5G_SDF_FILTER_ATTR_MAX
	GTP5G_SDF_FILTER_ATTR_MAX = __GTP5G_SDF_FILTER_ATTR_MAX - 1
)

const (
	GTP5G_FLOW_DESCRIPTION_ACTION = iota + 1
	GTP5G_FLOW_DESCRIPTION_DIRECTION
	GTP5G_FLOW_DESCRIPTION_PROTOCOL
	GTP5G_FLOW_DESCRIPTION_SRC_IPV4
	GTP5G_FLOW_DESCRIPTION_SRC_MASK
	GTP5G_FLOW_DESCRIPTION_DEST_IPV4
	GTP5G_FLOW_DESCRIPTION_DEST_MASK
	GTP5G_FLOW_DESCRIPTION_SRC_PORT
	GTP5G_FLOW_DESCRIPTION_DEST_PORT

	__GTP5G_FLOW_DESCRIPTION_ATTR_MAX
	GTP5G_FLOW_DESCRIPTION_ATTR_MAX = __GTP5G_FLOW_DESCRIPTION_ATTR_MAX - 1
)

const (
	GTP5G_FAR_ID = iota + 3
	GTP5G_FAR_APPLY_ACTION
	GTP5G_FAR_FORWARDING_PARAMETER

	GTP5G_FAR_RELATED_TO_PDR

	__GTP5G_FAR_ATTR_MAX
	GTP5G_FAR_ATTR_MAX = __GTP5G_FAR_ATTR_MAX - 1
)

const (
	FAR_ACTION_UPSPEC = 0x00
	FAR_ACTION_DROP   = 0x01
	FAR_ACTION_FORW   = 0x02
	FAR_ACTION_BUFF   = 0x04
	FAR_ACTION_MASK   = 0x07
	FAR_ACTION_NOCP   = 0x08
	FAR_ACTION_DUPL   = 0x10
)

const (
	GTP5G_FORWARDING_PARAMETER_OUTER_HEADER_CREATION = iota + 1
	GTP5G_FORWARDING_PARAMETER_FORWARDING_POLICY

	__GTP5G_FORWARDING_PARAMETER_ATTR_MAX
	GTP5G_FORWARDING_PARAMETER_ATTR_MAX = __GTP5G_FORWARDING_PARAMETER_ATTR_MAX - 1
)

const (
	GTP5G_OUTER_HEADER_CREATION_DESCRIPTION = iota + 1
	GTP5G_OUTER_HEADER_CREATION_O_TEID
	GTP5G_OUTER_HEADER_CREATION_PEER_ADDR_IPV4
	GTP5G_OUTER_HEADER_CREATION_PORT

	__GTP5G_OUTER_HEADER_CREATION_ATTR_MAX
	GTP5G_OUTER_HEADER_CREATION_ATTR_MAX = __GTP5G_OUTER_HEADER_CREATION_ATTR_MAX - 1
)

const (
	GTP5G_SDF_FILTER_ACTION_UNSPEC = iota

	GTP5G_SDF_FILTER_PERMIT

	__GTP5G_SDF_FILTER_ACTION_MAX
	GTP5G_SDF_FILTER_ACTION_MAX = __GTP5G_SDF_FILTER_ACTION_MAX - 1
)

const (
	GTP5G_SDF_FILTER_DIRECTION_UNSPEC = iota

	GTP5G_SDF_FILTER_IN
	GTP5G_SDF_FILTER_OUT

	__GTP5G_SDF_FILTER_DIRECTION_MAX
	GTP5G_SDF_FILTER_DIRECTION_MAX = __GTP5G_SDF_FILTER_DIRECTION_MAX - 1
)

const (
	GTP5G_QER_ID = iota + 3
	GTP5G_QER_GATE
	GTP5G_QER_MBR
	GTP5G_QER_GBR
	GTP5G_QER_CORR_ID
	GTP5G_QER_RQI
	GTP5G_QER_QFI
	GTP5G_QER_PPI
	GTP5G_QER_RCSR

	GTP5G_QER_RELATED_TO_PDR

	__GTP5G_QER_ATTR_MAX
	GTP5G_QER_ATTR_MAX = __GTP5G_QER_ATTR_MAX - 1
)

const (
	GTP5G_QER_MBR_UL_HIGH32 = iota + 1
	GTP5G_QER_MBR_UL_LOW8
	GTP5G_QER_MBR_DL_HIGH32
	GTP5G_QER_MBR_DL_LOW8

	__GTP5G_QER_MBR_ATTR_MAX
	GTP5G_QER_MBR_ATTR_MAX = __GTP5G_QER_MBR_ATTR_MAX - 1
)

const (
	GTP5G_QER_GBR_UL_HIGH32 = iota + 1
	GTP5G_QER_GBR_UL_LOW8
	GTP5G_QER_GBR_DL_HIGH32
	GTP5G_QER_GBR_DL_LOW8

	__GTP5G_QER_GBR_ATTR_MAX
	GTP5G_QER_GBR_ATTR_MAX = __GTP5G_QER_GBR_ATTR_MAX - 1
)
